### ISSUE TITLE
Does not work on 24.5.1

### ISSUE THREAD

**Issue by develuppro** [butorov/sentry-telegram#60] opened 2024-06-13 15:59 UTC
Hi. Can you check new version sentry 24.5.1  ?

**Comment by butorov** [comment] 2024-06-13 18:19
Hi @develuppro!
Do you have any logs or error traces displaying the problem?
I'm going to check the compatibility soon. Most probably this weekend or the next week.

**Comment by develuppro** [comment] 2024-06-13 19:01
@butorov 
![error](https://github.com/butorov/sentry-telegram/assets/38980201/59c51772-9f4b-4a41-b54f-4b178b7b08a8)

**Comment by butorov** [comment] 2024-06-27 00:16
Hi @develuppro and @cgabriel.
The issue is fixed in the 0.6.0 version of the plugin. I tested it on my Sentry 24.5.1 (will have the ability to check it on 24.6.0 soon). Feel free to update.
Thank you for reporting!

The thing was as in https://github.com/getsentry/sentry/pull/71880 Sentry's team has changed the signature of a `safe_execute()` function, which I use in a way, similar to the built-in plugins. The change affected built-in integrations/plugins as well.
The whole pull request shows that we can continue using the updated function with no worries.

**Closed by butorov** 2024-06-27 00:16 UTC
